defmodule AtvApi.FactoryGrntiList do

  @grnti_list [
     %{id: 000000, has_children: true, title: "ОБЩЕСТВЕННЫЕ НАУКИ В ЦЕЛОМ"},
     %{id: 000800, has_children: false, title: "Общественные науки и идеология"},
     %{id: 000900, has_children: false, title: "История общественных наук"},
     %{id: 001100, has_children: false, title: "Современное состояние общественных наук"},
     %{id: 001300, has_children: false, title: "Научные общества, съезды, конгрессы, конференции, симпозиумы по общественным наукам"},
     %{id: 001700, has_children: false, title: "Международное сотрудничество в области общественных наук"},
     %{id: 002100, has_children: false, title: "Организация научно-исследовательской работы в области общественных наук"},
     %{id: 002900, has_children: false, title: "Информационная деятельность в общественных науках"},
     %{id: 003300, has_children: false, title: "Терминология общественных наук"},
     %{id: 003900, has_children: false, title: "Пропаганда и популяризация общественных наук"},
     %{id: 004500, has_children: false, title: "Преподавание общественных наук"},
     %{id: 007700, has_children: false, title: "Математическое моделирование в общественных и гуманитарных науках"},
     %{id: 007900, has_children: false, title: "Кадры обществоведов"},
     %{id: 020000, has_children: true, title: "ФИЛОСОФИЯ"},
     %{id: 020100, has_children: true, title: "Общие вопросы философии"},
     %{id: 020107, has_children: false, title: "Философия как наука"},
     %{id: 020113, has_children: false, title: "Научные общества, съезды, конгрес-сы, конференции, симпозиумы по философии"},
     %{id: 020117, has_children: false, title: "Международное сотрудничество в области философии"},
     %{id: 020121, has_children: false, title: "Организация научно-исследователь-ской работы в области философии"},
     %{id: 020129, has_children: false, title: "Информационная деятельность в области философии"},
     %{id: 020139, has_children: false, title: "Пропаганда и популяризация философских знаний"},
     %{id: 020145, has_children: false, title: "Преподавание философии"},
     %{id: 020179, has_children: false, title: "Кадры философов"},
     %{id: 021100, has_children: true, title: "Общие проблемы современной философии"},
     %{id: 021121, has_children: false, title: "Отдельные направления и школы современной философии"},
     %{id: 021191, has_children: false, title: "Философия в отдельных странах. Персоналия"},
     %{id: 021500, has_children: true, title: "Общефилософские проблемы"},
     %{id: 021521, has_children: false, title: "Бытие. Материя. Сознание"},
     %{id: 021531, has_children: false, title: "Познание"},
     %{id: 021541, has_children: false, title: "Законы и категории диалектики"},
     %{id: 021551, has_children: false, title: "Философия человека"},
     %{id: 021561, has_children: false, title: "Философия ценностей"},
     %{id: 021599, has_children: false, title: "Другие общефилософские проблемы"},
     %{id: 022100, has_children: true, title: "Логика"},
     %{id: 022105, has_children: false, title: "Общие проблемы диалектической логики"},
     %{id: 022111, has_children: false, title: "Современное состояние логики"},
     %{id: 022121, has_children: false, title: "Логические формы и законы"},
     %{id: 022131, has_children: false, title: "Логические системы и исчисления"},
     %{id: 022141, has_children: false, title: "Отдельные понятия и проблемы логики"},
     %{id: 023100, has_children: true, title: "Философия и методология науки"},
     %{id: 023101, has_children: false, title: "Общие вопросы"},
     %{id: 023121, has_children: false, title: "Философские и методологические проблемы науки и научного знания в целом"},
     %{id: 023131, has_children: false, title: "Философские и методологические проблемы математических, естественных и технических наук"},
     %{id: 023155, has_children: false, title: "Философские и методологические проблемы общественных наук"},
     %{id: 024100, has_children: true, title: "Социальная философия"},
     %{id: 024101, has_children: false, title: "Общие вопросы"},
     %{id: 024111, has_children: false, title: "Общие проблемы современной социальной философии"},
     %{id: 024121, has_children: false, title: "Общество в целом. Социальное развитие"},
     %{id: 024131, has_children: false, title: "Социальные классы, общности и группы"},
     %{id: 024141, has_children: false, title: "Сферы социальной жизни. Социальные явления и институты"},
     %{id: 024151, has_children: false, title: "Личность, массы и общество"},
     %{id: 025100, has_children: true, title: "Этика"},
     %{id: 025111, has_children: false, title: "Современное состояние этики"},
     %{id: 025115, has_children: false, title: "Общеэтические категории и проблемы"},
     %{id: 025125, has_children: false, title: "Этика общественных институтов и отдельных областей жизни и деятельности"},
     %{id: 025145, has_children: false, title: "Нравственное воспитание"},
     %{id: 026100, has_children: true, title: "Эстетика"},
     %{id: 026111, has_children: false, title: "Современное состояние эстетики"},
     %{id: 026115, has_children: false, title: "Общеэстетические категории и проблемы"},
     %{id: 026125, has_children: false, title: "Эстетика природы и человеческой деятельности"},
     %{id: 026131, has_children: false, title: "Эстетика искусства"},
     %{id: 026145, has_children: false, title: "Эстетическое воспитание"},
     %{id: 027100, has_children: false, title: "Философия религии и атеизма"},
     %{id: 029100, has_children: true, title: "История философии"},
     %{id: 029101, has_children: false, title: "Общие вопросы"},
     %{id: 029109, has_children: false, title: "Всемирная история философии"},
     %{id: 029115, has_children: false, title: "История марксистско-ленинской философии"},
     %{id: 029191, has_children: false, title: "История философии в отдельных странах"},
     %{id: 030000, has_children: true, title: "ИСТОРИЯ. ИСТОРИЧЕСКИЕ НАУКИ"},
     %{id: 030100, has_children: false, title: "Общие вопросы исторических наук"},
     %{id: 030106, has_children: false, title: "Философия истории"},
     %{id: 030107, has_children: false, title: "Методология и методы исследования исторической науки"},
     %{id: 030109, has_children: false, title: "История исторической науки. Персоналия"},
     %{id: 030111, has_children: false, title: "Современное состояние исторической науки"},
     %{id: 030113, has_children: false, title: "Съезды, конгрессы, конференции, симпозиумы, семинары в области исторических наук"},
     %{id: 030117, has_children: false, title: "Международное сотрудничество в области исторических наук"},
     %{id: 030121, has_children: false, title: "Организация научно-исследовательской работы в области исторических наук"},
     %{id: 030129, has_children: false, title: "Информационная деятельность в исторических науках"},
     %{id: 030139, has_children: false, title: "Пропаганда и популяризация исторических знаний"},
     %{id: 030145, has_children: false, title: "Преподавание истории"},
     %{id: 030179, has_children: false, title: "Кадры историков"},
     %{id: 030900, has_children: true, title: "Всеобщая история"},
     %{id: 030903, has_children: false, title: "Всеобщая история в целом"},
     %{id: 030921, has_children: false, title: "Первобытное общество"},
     %{id: 030923, has_children: false, title: "Древний мир (до V в.н.э.)"},
     %{id: 030925, has_children: false, title: "Средние века (V - XVI вв.)"},
     %{id: 030931, has_children: false, title: "Новая история (XVII - XIX вв.)"},
     %{id: 030955, has_children: false, title: "Новейшая история (c XX в. )"},
     %{id: 031500, has_children: false, title: "История Азербайджана"},
     %{id: 031600, has_children: false, title: "История Армении"},
     %{id: 031700, has_children: false, title: "История Белоруссии"},
     %{id: 031800, has_children: false, title: "История Грузии"},
     %{id: 031900, has_children: false, title: "(История отдельных стран) (Исключено с2004. Перенесено в 03.91)"},
     %{id: 032000, has_children: false, title: "История Казахстана"},
     %{id: 032100, has_children: false, title: "История Киргизии"},
     %{id: 032200, has_children: false, title: "История Молдавии"},
     %{id: 032300, has_children: true, title: "История России"},
     %{id: 032307, has_children: false, title: "Историография и источниковедение истории России"},
     %{id: 032323, has_children: false, title: "История России в древности ( до середины XII в.)"},
     %{id: 032325, has_children: false, title: "История России в средние века (с середины XII в. до конца XVI в.)"},
  ]

  def grnti_list, do: @grnti_list

end