defmodule AtvApi.FactoryFosList do

  @fos_list [
    %{id: "010000", title: "Natural Sciences"},
    %{id: "020000", title: "Engineering and Technology"},
    %{id: "030000", title: "Medical and Health Sciences"},
    %{id: "040000", title: "Agricultural Sciences"},
    %{id: "050000", title: "Social Sciences"},
    %{id: "060000", title: "Humanities"},
    %{id: "010100", title: "Mathematics"},
    %{id: "010200", title: "Computer and information sciences"},
    %{id: "010300", title: "Physical sciences and astronomy"},
    %{id: "010400", title: "Chemical sciences"},
    %{id: "010500", title: "Earth and related environmental sciences"},
    %{id: "010600", title: "Biological sciences"},
    %{id: "010700", title: "Other natural sciences"},
    %{id: "020100", title: "Civil engineering"},
    %{id: "020200", title: "Electrical eng, electronic eng"},
    %{id: "020300", title: "Mechanical engineering"},
    %{id: "020400", title: "Chemical engineering"},
    %{id: "020500", title: "Materials engineering"},
    %{id: "020600", title: "Medical engineering"},
    %{id: "020700", title: "Environmental engineering"},
    %{id: "020800", title: "Environmental biotechnology"},
    %{id: "020900", title: "Industrial biotechnology"},
    %{id: "021000", title: "Nano-technology"},
    %{id: "021100", title: "Other engineering and technologies"},
    %{id: "030100", title: "Basic medical research"},
    %{id: "030200", title: "Clinical medicine"},
    %{id: "030300", title: "Health sciences"},
    %{id: "040100", title: "Agriculture, forestry, fisheries"},
    %{id: "040200", title: "Animal and dairy science"},
    %{id: "040300", title: "Veterinary science"},
    %{id: "040400", title: "Other agricultural science"},
    %{id: "050100", title: "Psychology"},
    %{id: "050200", title: "Economics and business"},
    %{id: "050300", title: "Educational sciences"},
    %{id: "050400", title: "Sociology"},
    %{id: "050500", title: "Law"},
    %{id: "050600", title: "Political science"},
    %{id: "050700", title: "Social and economic geography"},
    %{id: "050800", title: "Media and communication"},
    %{id: "050900", title: "Other social sciences"},
    %{id: "060100", title: "History and archaeology"},
    %{id: "060200", title: "Languages and literature"},
    %{id: "060300", title: "Philosophy, ethics and religion"},
    %{id: "060400", title: "Art"},
    %{id: "060500", title: "Other Humanities"},
    %{id: "0101PN", title: "Mathematics, applied"},
    %{id: "0101PO", title: "Mathematics, interdisciplinary applications"},
    %{id: "0101PQ", title: "Mathematics"},
    %{id: "0101UR", title: "Physics, mathematical"},
    %{id: "0101XY", title: "Statistics & probability"},
    %{id: "0102EP", title: "Computer science, artificial intelligence"},
    %{id: "0102ER", title: "Computer science, cybernetics"},
    %{id: "0102ET", title: "computer science, information systems"},
    %{id: "0102EV", title: "computer science, interdisciplinary applications"},
    %{id: "0102EW", title: "computer science, software engineering"},
    %{id: "0102EX", title: "computer science, theory & methods"},
    %{id: "0103AA", title: "Acoustics"},
    %{id: "0103BU", title: "Astronomy & astrophysics"},
    %{id: "0103SY", title: "Optics"},
    %{id: "0103UB", title: "Physics, applied"},
    %{id: "0103UF", title: "Physics, fluids & plasmas"},
    %{id: "0103UH", title: "Physics, atomic, molecular & chemical"},
    %{id: "0103UI", title: "Physics, multidisciplinary"},
    %{id: "0103UK", title: "Physics, condensed matter"},
    %{id: "0103UN", title: "Physics, nuclear"},
    %{id: "0103UP", title: "Physics, particles & fields"},
    %{id: "0104DW", title: "Chemistry, applied"},
    %{id: "0104DY", title: "Chemistry, multidisciplinary"},
    %{id: "0104EA", title: "Chemistry, analytical"},
    %{id: "0104EC", title: "Chemistry, inorganic & nuclear"},
    %{id: "0104EE", title: "Chemistry, organic"},
    %{id: "0104EI", title: "Chemistry, physical"},
    %{id: "0104FI", title: "Crystallography"},
    %{id: "0104HQ", title: "Electrochemistry"},
    %{id: "0104UY", title: "Polymer science"},
    %{id: "0105GC", title: "Geochemistry & geophysics"},
    %{id: "0105JA", title: "Environmental sciences"},
    %{id: "0105KV", title: "Geography, physical"},
    %{id: "0105KY", title: "Geology"},
    %{id: "0105LE", title: "Geosciences, multidisciplinary"},
    %{id: "0105QQ", title: "Meteorology & atmospheric sciences"},
    %{id: "0105RE", title: "Mineralogy"},
    %{id: "0105SI", title: "Oceanography"},
    %{id: "0105TE", title: "Paleontology"},
    %{id: "0105ZR", title: "Water resources"},
    %{id: "0106BD", title: "Biodiversity conservation"},
    %{id: "0106CO", title: "Biochemical research methods"},
    %{id: "0106CQ", title: "Biochemistry & molecular biology"},
    %{id: "0106CU", title: "Biology"},
    %{id: "0106DA", title: "Biophysics"},
    %{id: "0106DE", title: "Plant sciences"},
    %{id: "0106DR", title: "Cell biology"},
    %{id: "0106GU", title: "Ecology"},
    %{id: "0106HT", title: "Evolutionary biology"},
    %{id: "0106HY", title: "Developmental biology"},
    %{id: "0106IY", title: "Entomology"},
    %{id: "0106KM", title: "Genetics & Heredity"},
    %{id: "0106MC", title: "Mathematical & computational biology"},
    %{id: "0106OU", title: "Limnology"},
    %{id: "0106PI", title: "Marine & freshwater biology"},
    %{id: "0106QU", title: "Microbiology"},
    %{id: "0106RQ", title: "Mycology"},
    %{id: "0106TA", title: "Ornithology"},
    %{id: "0106WF", title: "reproductive biology"},
    %{id: "0106ZE", title: "virology"},
    %{id: "0107RO", title: "Multidisciplinary sciences"},
    %{id: "0201FA", title: "Construction & building technology"},
    %{id: "0201IM", title: "Engineering, civil"},
    %{id: "0201YR", title: "Transportation science & technology"},
    %{id: "0202AC", title: "Automation & control systems"},
    %{id: "0202ES", title: "computer science, hardware & architecture"},
    %{id: "0202EU", title: "Communication"},
    %{id: "0202IQ", title: "Engineering, electrical & electronic"},
    %{id: "0202RB", title: "Robotics"},
    %{id: "0202YE", title: "Telecommunications"},
    %{id: "0203AI", title: "Engineering, aerospace"},
    %{id: "0203DT", title: "Thermodynamics"},
    %{id: "0203IU", title: "Engineering, mechanical"},
    %{id: "0203PU", title: "Mechanics"},
    %{id: "0203RY", title: "Nuclear science & technology"},
    %{id: "0204II", title: "Engineering, chemical"},
    %{id: "0205PJ", title: "Materials science, paper & wood"},
    %{id: "0205PK", title: "Materials science, ceramics"},
    %{id: "0205PM", title: "Materials science, multidisciplinary"},
    %{id: "0205PZ", title: "metallurgy & metallurgical engineering"},
    %{id: "0205QF", title: "Materials science, characterization & testing"},
    %{id: "0205QG", title: "Materials science, coatings & films"},
    %{id: "0205QH", title: "Materials science, composites"},
    %{id: "0205QJ", title: "Materials science, textiles"},
    %{id: "0206CT", title: "Cell & tissue engineering"},
    %{id: "0206IG", title: "Engineering, biomedical"},
    %{id: "0206PW", title: "Medical laboratory technology"},
    %{id: "0207ID", title: "Energy & fuels"},
    %{id: "0207IH", title: "Engineering, environmental"},
    %{id: "0207IL", title: "Engineering, marine"},
    %{id: "0207IO", title: "Engineering, ocean"},
    %{id: "0207IP", title: "Engineering, petroleum"},
    %{id: "0207IX", title: "Engineering, geological"},
    %{id: "0207SR", title: "Remote sensing"},
    %{id: "0207ZQ", title: "Mining & mineral processing"},
    %{id: "0208DB", title: "Biotechnology & applied microbiology"},
    %{id: "0209QE", title: "Materials science, biomaterials"},
    %{id: "0210NS", title: "Nanoscience & nanotechnology"},
    %{id: "0211IF", title: "Engineering, multidisciplinary"},
    %{id: "0211IJ", title: "Engineering, industrial"},
    %{id: "0211IK", title: "Engineering, manufacturing"},
    %{id: "0211JY", title: "Food science & technology"},
    %{id: "0211OA", title: "Instruments & Instrumentation"},
    %{id: "0211RA", title: "Microscopy"},
    %{id: "0211UE", title: "Imaging science & photographic technology"},
    %{id: "0211XQ", title: "Spectroscopy"},
    %{id: "0301AY", title: "Anatomy & morpheology"},
    %{id: "0301DX", title: "Chemistry, medicinal"},
    %{id: "0301EQ", title: "Psychology, clinical"},
    %{id: "0301NI", title: "Immunology"},
    %{id: "0301QA", title: "Medicine, research & experimental"},
    %{id: "0301RU", title: "Neurosciences"},
    %{id: "0301TM", title: "Pathology"},
    %{id: "0301TU", title: "Pharmacology & pharmacy"},
    %{id: "0301UM", title: "Physiology"},
    %{id: "0301YO", title: "Toxicology"},
    %{id: "0302AQ", title: "Allergy"},
    %{id: "0302AZ", title: "Andrology"},
    %{id: "0302BA", title: "Anesthesiology"},
    %{id: "0302DM", title: "Oncology"},
    %{id: "0302DQ", title: "Cardiac & cardiovascular systems"},
    %{id: "0302DS", title: "Critical care medicine"},
    %{id: "0302FF", title: "Emergency medicine"},
    %{id: "0302FY", title: "Dentistry,oral surgery & medicine"},
    %{id: "0302GA", title: "Dermatology"},
    %{id: "0302IA", title: "Endocrinology & metabolism"},
    %{id: "0302KI", title: "Gastroenterology & hepatology"},
    %{id: "0302LI", title: "Geriatrics & gerontology"},
    %{id: "0302LJ", title: "Gerontology"},
    %{id: "0302MA", title: "Hematology"},
    %{id: "0302OI", title: "Integrative & complementary medicine"},
    %{id: "0302PY", title: "Medicine, general & internal"},
    %{id: "0302RT", title: "Clinical neurology"},
    %{id: "0302RX", title: "Neuroimaging"},
    %{id: "0302SD", title: "Obstetrics & gynecology"},
    %{id: "0302SU", title: "Ophthalmology"},
    %{id: "0302TC", title: "Orthopedics"},
    %{id: "0302TD", title: "Otorhinolaryngology"},
    %{id: "0302TQ", title: "Pediatrics"},
    %{id: "0302VE", title: "Psychiatry"},
    %{id: "0302VY", title: "Radiology, nuclear medicine & medical imaging"},
    %{id: "0302WE", title: "Respiratory system"},
    %{id: "0302WH", title: "Rheumatology"},
    %{id: "0302YA", title: "Surgery"},
    %{id: "0302YP", title: "Transplantation"},
    %{id: "0302ZD", title: "Peripheral vascular disease"},
    %{id: "0303GM", title: "Substance abuse"},
    %{id: "0303HL", title: "Health care sciences & services"},
    %{id: "0303LQ", title: "Health policy & services"},
    %{id: "0303ML", title: "Primary health care"},
    %{id: "0303NE", title: "Public, environmental & occupational health"},
    %{id: "0303NN", title: "Infectious diseases"},
    %{id: "0303OO", title: "Medical ethics"},
    %{id: "0303OP", title: "Medicine, legal"},
    %{id: "0303PT", title: "Medical informatics"},
    %{id: "0303RZ", title: "Nursing"},
    %{id: "0303SA", title: "Nutrition & Dietetics"},
    %{id: "0303TI", title: "Parasitology"},
    %{id: "0303VP", title: "Psychology, psychoanalysis"},
    %{id: "0303WC", title: "Rehabilitation"},
    %{id: "0303WV", title: "Social sciences, biomedical"},
    %{id: "0303XW", title: "Sport sciences"},
    %{id: "0303YU", title: "Tropical medicine"},
    %{id: "0401AH", title: "Agriculture, multidisciplinary"},
    %{id: "0401AM", title: "Agronomy"},
    %{id: "0401JU", title: "Fisheries"},
    %{id: "0401KA", title: "Forestry"},
    %{id: "0401MU", title: "Horticulture"},
    %{id: "0401XE", title: "Soil science"},
    %{id: "0402AD", title: "Agriculture, dairy & animal science"},
    %{id: "0403ZC", title: "Veterinary sciences"},
    %{id: "040500", title: "Some other agricultural science"},
    %{id: "0405AE", title: "Agricultural engineering"},
    %{id: "0405JY", title: "Food science & technology"},
    %{id: "0501BV", title: "Psychology, biological"},
    %{id: "0501CN", title: "Behavioral sciences"},
    %{id: "0501HI", title: "Psychology, educational"},
    %{id: "0501JI", title: "Ergonomics"},
    %{id: "0501MY", title: "Psychology, developmental"},
    %{id: "0501NQ", title: "Psychology, applied"},
    %{id: "0501VI", title: "Psychology"},
    %{id: "0501VJ", title: "Psychology, multidisciplinary"},
    %{id: "0501VS", title: "Psychology, mathematical"},
    %{id: "0501VX", title: "Psychology, experimental"},
    %{id: "0501WQ", title: "Psychology, social"},
    %{id: "0502DI", title: "Business"},
    %{id: "0502DK", title: "Business, finance"},
    %{id: "0502GY", title: "Economics"},
    %{id: "0502NM", title: "Industrial relations & labor"},
    %{id: "0502PC", title: "Management"},
    %{id: "0502PE", title: "Operations research & management science"},
    %{id: "0503HA", title: "Education & educational research"},
    %{id: "0503HB", title: "Education, scientific disciplines"},
    %{id: "0503HE", title: "Education, special"},
    %{id: "0504BF", title: "Anthropology"},
    %{id: "0504FU", title: "Demography"},
    %{id: "0504JM", title: "Ethnic studies"},
    %{id: "0504JO", title: "Family studies"},
    %{id: "0504PS", title: "Social sciences mathematical methods"},
    %{id: "0504WM", title: "Social issues"},
    %{id: "0504WY", title: "Social work"},
    %{id: "0504XA", title: "Sociology"},
    %{id: "0504ZK", title: "Women&"},
    %{id: "0505FE", title: "Criminology & penology"},
    %{id: "0505OM", title: "Law"},
    %{id: "0506OE", title: "International relations"},
    %{id: "0506UU", title: "Political science"},
    %{id: "0506VM", title: "Public administration"},
    %{id: "0507BM", title: "Area studies"},
    %{id: "0507JB", title: "Environmental studies"},
    %{id: "0507KU", title: "Geography"},
    %{id: "0507UQ", title: "Planning & development"},
    %{id: "0507YQ", title: "Transportation"},
    %{id: "0507YY", title: "Urban studies"},
    %{id: "0508NU", title: "Information science& library science"},
    %{id: "0509EN", title: "Cultural studies"},
    %{id: "0509MW", title: "hospitality, leisure, sport & tourism"},
    %{id: "0509OR", title: "Asian studies"},
    %{id: "0509WU", title: "Social sciences, interdisciplinary"},
    %{id: "0601BI", title: "Archaeology"},
    %{id: "0601MM", title: "History"},
    %{id: "0601MQ", title: "History & philosophy of science"},
    %{id: "0601MR", title: "History of social sciences"},
    %{id: "0601QK", title: "Medieval & renaissance studies"},
    %{id: "0602EO", title: "Classics"},
    %{id: "0602JW", title: "Folklore"},
    %{id: "0602OT", title: "Linguistics"},
    %{id: "0602OX", title: "Literary theory & criticism"},
    %{id: "0602OY", title: "Language & linguistics"},
    %{id: "0602OZ", title: "Literary reviews"},
    %{id: "0602PA", title: "Literature"},
    %{id: "0602PD", title: "Literature, African, Australian, Canadian"},
    %{id: "0602PF", title: "Literature, American"},
    %{id: "0602PG", title: "Literature, British isles"},
    %{id: "0602PH", title: "Literature, German, Dutch, Scandinavian"},
    %{id: "0602QC", title: "Literature, romance"},
    %{id: "0602QD", title: "Literature, Slavic"},
    %{id: "0602UT", title: "Poetry"},
    %{id: "0603HF", title: "Ethics"},
    %{id: "0603UA", title: "Philosophy"},
    %{id: "0603YI", title: "Religion"},
    %{id: "0604BK", title: "Architecture"},
    %{id: "0604BP", title: "Art"},
    %{id: "0604FS", title: "Dance"},
    %{id: "0604JS", title: "Film, radio, television"},
    %{id: "0604RP", title: "Music"},
    %{id: "0604YG", title: "Theater"},
    %{id: "0605BQ", title: "Humanities, multidisciplinary"},
  ]

  def fos_list, do: @fos_list

end